src/ops/math.rs
This was quite straightforward.
=> Implemented the Neg operator.

core/src/ops/array/pad.rs, core/src/ops/array/slice.rs, core/src/ops/mod.rs, core/src/plan.rs, core/src/pulse/delay.rs, core/src/pulse/mod.rs
=> Generalize pulse

.github/workflows/windows.yml, Cargo.toml, cli/Cargo.toml, cli/src/main.rs, cli/src/rusage.rs, core/Cargo.toml, core/src/lib.rs, core/src/ops/cnn/patches.rs
=> More windows ci

linalg/arm32/armv7neon/armv7neon_ssigmoid_4.tmpl, linalg/arm32/armv7neon/armv7neon_stanh_4.tmpl
=> replace lrd by adr

.travis/bundle-entrypoint.sh, .travis/native.sh
=> qam test and bench setup

.github/workflows/cross-platform.yml, .travis/cross.sh, CHANGELOG.md, onnx/Cargo.toml, onnx/src/model.rs, tensorflow/Cargo.toml, tensorflow/src/model.rs
=> Wasm build

core/src/ops/matmul/mir.rs
=> fix mmmwrapper dispatcher again

hir/src/lib.rs
The other change is done by rustfmt.
=> add InferenceSimplePlan to prelude of tract_hir

core/src/ops/array/pad.rs, harness/onnx-test-suite/node-1.6.0.txt, harness/onnx-test-suite/node-1.7.0.txt, onnx/src/ops/array/pad.rs, onnx/src/ops/array/slice.rs, onnx/src/ops/mod.rs, onnx/src/ops/resize.rs
=> Onnx resize

core/src/model/typed.rs, core/src/ops/invariants.rs, core/src/optim/mod.rs
=> Play with outletmap

core/src/ops/change_axes.rs
=> change_axis fix

CHANGELOG.md, linalg/src/frame/mmm/kernel.rs, linalg/src/frame/mmm/tests.rs, linalg/src/generic/mmm.rs, linalg/src/lib.rs
=> Add generic multiplication for i8 u8

nnef/src/framework.rs
I reviewed the code again, developer is still able to call the `proto_model_for_read` method with reader parameter. In this case the gzip detection is skipped. I moved the check inside `proto_model_for_read`, so that we can avoid this issue.
BTW, do you have `mobilenet_v2_1.0.onnx.nnef.tar` file for testing. I tried to create one with  decompress and compress again with tar command. But it give me this error: `Error: Wrong magic number`.
=> Refactored the fix for NNEF gzip file detection

doc/intro.md
I just stumbled across this project and find it interesting. I thought I could help out with a few small changes to the documentation to get started. I hope to contribute more in the future 
Thanks!
=> Intro Page Cleanup in Documentation

.travis/native.sh, cli/src/dump.rs, cli/src/main.rs, cli/src/params.rs, cli/src/run.rs, cli/src/utils.rs
Added an assert-op-count argument to the run and dump subcommands
=> Added assert-op-count to cli

core/src/ops/cnn/conv/proptest_q.rs
The scales for a and b were not tested in the conv proptests. I added them as the proptest is not much longer to run with them. 
It failed at first because the reference did not take those scales into account, but in tract the test passes. 
I will rebase this PR on main when the group PR is merged, as there will probably be conflicts.
=> add scales to proptest, fix reference

core/src/lib.rs, onnx/src/model.rs
Fixes: https://github.com/sonos/tract/issues/499
=> Fix Onnx::parse causing a panic if the proto does not contain a graph

linalg/arm64/arm64simd/arm64simd_mmm_f32_12x8_core.tmpl, linalg/arm64/arm64simd/arm64simd_mmm_f32_8x8_core.tmpl, linalg/build.rs
Minor indentation fix while at it.
=> linalg build system: Fix template partials when building for ARM64 on "backslashy" platforms.

hir/src/ops/array/array_feature_extractor.rs, hir/src/ops/array/mod.rs, onnx/src/ops/array/mod.rs
Add an implementation for `ArrayFeatureExtractor` using the `Gather` operator
=> Add ArrayFeatureExtractor operator

linalg/build.rs
Thanks for bearing with me, reopening #601 with fixes to ensure it compiles properly.
=> Fix inconsistent builds by sorting dir_entries

tensorflow/build.rs
Same as https://github.com/sonos/tract/pull/603, but in a different project. :)
=> Fix inconsistent build in the tensorflow crate

.travis/cross.sh, Cargo.toml
=> tweak build-override

data/src/tensor.rs
- fix: (l803) tensor as_uniform propagate original datum_type
- style: removed few trailing spaces
- style: format
=> [WIP] fix: tensor as_uniform propagate original datum_type

nnef/src/ops/core.rs, nnef/src/ops/nnef/deser.rs, nnef/src/ops/nnef/mod.rs
Reverts sonos/tract#665. Been a bit too fast.
=> Revert "Fix: nnef issues"

nnef/src/ops/core.rs, nnef/src/ops/nnef/deser.rs, nnef/src/ops/nnef/mod.rs, nnef/src/ops/nnef/ser.rs
- move tract_core arc and hyperbolic sin/tan/cos to default NNEF ops following the Spec
- replace repeat agument by repeats to follow NNEF Spec
=> Fix torch to nnef issues

linalg/arm32/armv7neon/dispatcher.tmpliq, linalg/arm32/armvfpv2/dispatcher.tmpliq
Fixes #661, see the issue for more details.
=> Added alternative jumptable imple on 32bit arm if os==android.

nnef/src/ops/core/cast.rs
=> Fix nnef ser q

data/src/dim/tree.rs, nnef/src/ast.rs, nnef/src/deser.rs, nnef/src/ops/core/source.rs, nnef/src/ops/nnef/ser.rs, nnef/src/ser.rs
=> fix around source with sym chapes

core/src/ops/math/mod.rs, core/src/ops/matmul/lir_unary.rs, core/src/ops/quant.rs, linalg/src/frame/mmm/fuse.rs, linalg/src/frame/mmm/kernel.rs, linalg/src/generic.rs, linalg/src/generic/mmm.rs, linalg/src/generic/rounding.rs, linalg/src/lib.rs
Not really used, but it wasn't working.
I've also moved the function computing the multiplier and the shift of a given scale in a dedicated function and changed its validity range.
=> Fix f32 scaling

core/src/model/fact.rs, core/src/ops/array/slice.rs, hir/src/infer/model.rs
=> various fixes for slice with tdim boundaries

core/src/framework.rs, nnef/src/registry.rs
https://github.com/EmbarkStudios/cervo/issues/22
=> make Framework Send and Sync

data/src/tensor.rs
For types that can be converted to a slice, it is very dangerous to
use a null pointer as an initial pointer value. Even when a slice is
length zero, the pointer passed to from_raw_parts cannot be null. The
same goes for calls to copy/copy_nonoverlapping; even if the size is 0
the pointers may not be null (memcpy has the same rule). Both situations
are encountered through the test called crop_then_down_3. This can be
detected by running the tests -Zbuild-std
--target=x86_64-unknown-linux-gnu (or whatever your host is), which will
rebuild the standard library with its debug assertions enabled, which
check for these preconditions.
=> Fix UB by creating uninit Tensors with a non-null pointer

cli/src/params.rs
For #742, the assert changes I made.
=> relax and add some diagnostics to asserts

cli/src/utils.rs
Fix CLI regression happening since commit `bf8ba8a45ae5569ae5981dc5b440a8d4ab432b0a`
Where `--check-output` with model containing multiple outputs: does not compare correct labels anymore.
=> fix: check properly each output in case >1 outputs

core/src/ops/matmul/mir_unary.rs
=> missed a "magic axes at the end" bug

nnef/src/ops/nnef/deser.rs
- Allow stride in slice op from NNEF format
=> feat: support stride in slice

core/src/plan.rs
Hello!
Fixed a panic @mbrunel saw
The boolean returned by matches wasn't actually checked.
=> Fix plan input fact checking

onnx-opl/src/random.rs, onnx/src/ops/random.rs
=> fix law selection

core/src/ops/cnn/conv/unary.rs
=> dont remove last geo axis in conv

nnef/src/framework.rs
`File::open`ing a directory can fail on an unnamed OS.
With this, a `cargo test`  in `nnef` completes successfully, whereas the `nnef::test_json_resource::load_model_with_json_resource` test currently fails on the `main` branch.
Building the python wheels with https://github.com/sonos/tract/pull/948 also succeeds locally. (After installing `cibuildwheel` locally, `python -m cibuildwheel ffi/py --output-dir wheelhouse --config-file "" --only "" --platform windows` can be used without `pipx` and so on)
=> nnef: ignore directories when loading a model from a path

.github/workflows/pydoc.yml, ffi/py/docs/fact.md, ffi/py/docs/index.md, ffi/py/docs/inference_model.md, ffi/py/docs/model.md, ffi/py/docs/nnef.md, ffi/py/docs/onnx.md, ffi/py/docs/runnable.md, ffi/py/docs/value.md, ffi/py/mkdocs.yml, ffi/py/requirements-docs.txt, ffi/py/tract/__init__.py, ffi/py/tract/inference_model.py, ffi/py/tract/model.py, ffi/py/tract/nnef.py, ffi/py/tract/onnx.py
* some doc (root, nnef)
* more pdoc
* wip on pydoc
* wip, switchinb to mkdocstrings
* test doc build in CI
* yaml syntax fix
* yaml syntax fix
* mike needs git setup
* fix gh-pages fetch
* try to publish
* publish on release
* more method doc
=> Python api doc, wip (#979)

cli/src/params.rs, core/src/ops/cnn/conv/unary.rs, core/src/ops/cnn/pools.rs, hir/src/ops/array/broadcast.rs, hir/src/ops/expandable.rs
=> Fixes for 985

core/src/ops/array/mod.rs, core/src/ops/array/trilu.rs, harness/onnx-test-suite/node-1.10.2.txt, harness/onnx-test-suite/node-1.11.0.txt, harness/onnx-test-suite/node-1.12.0.txt, harness/onnx-test-suite/node-1.13.0.txt, harness/onnx-test-suite/node-1.7.0.txt, harness/onnx-test-suite/node-1.9.0.txt, nnef/src/ops/core.rs, nnef/src/ops/core/trilu.rs, onnx/src/ops/array/mod.rs, onnx/src/ops/array/trilu.rs, onnx/src/tensor.rs
=> Onnx trilu

nnef/src/ast/quant.rs, nnef/src/framework.rs
* sanitize identifier
* Fix with excaped identifier instead
* Make extended syntax opt-in with nnef-extended-identifier option
* Fix tag
* Add test
=> Fix quant ser (#1013)

onnx/src/ops/logic.rs
Fixes https://github.com/sonos/tract/issues/1029
=> Add missing implementation of `nboutputs` for If Operator

examples/onnx-mobilenet-v2/README.md, examples/onnx-mobilenet-v2/ci.sh, onnx/src/model.rs, onnx/src/tensor.rs, tensorflow/src/model.rs
Fix Issue https://github.com/sonos/tract/issues/1066#issuecomment-1528933145.
=> Fix Runtime Error of the ONNX Example due to `memmap2` on WebAssembly Platform

nnef/src/ops/core/broadcast.rs
Similar modifications were done for other core component but not for the broadcast.
=> Allow new symbol for shape

data/src/dim/tree.rs
Perhaps it's not your style, but thought I'd raise since I spent this morning messing with it.
=> feat: tree changes

examples/nnef-dump-mobilenet-v2/README.md, examples/onnx-mobilenet-v2/README.md, examples/tflite-mobilenet-v3/README.md
Hello, the examples didn't work for me, I think there are missing conversions there.
=> Add forgotten conversions in examples

onnx/src/ops/array/split.rs
Split13 had incomplete type inference.
=> fix incomplete type analyse for Split13

hir/src/ops/nn/reduce.rs
=> cast back to tdim in reduce<sum>

core/src/plan.rs
=> info! -> debug!

core/src/model/fact.rs, core/src/ops/array/range.rs, core/src/ops/math/mod.rs, data/src/dim/mod.rs
- (S/S) support simplify to 1 (for any same symbol)  
- Relax arange attribute prerequisite, to be "scalar" castable.
=> Fix: add div support of (S/S) and relax arange op attributes prerequisite 

onnx/src/ops/resize.rs
=> spurious debug in onnx resize loader

core/src/model/graph.rs, core/src/ops/array/topk.rs
=> fix: topk core op index_axis_inplace -> collapse_axis

metal/src/kernels/nn/nn_ops.metal, metal/src/kernels/nn/rms_norm.rs
Newly implemented RMS norm metal kernels had some issues with F16 precision. This PR fixes the issue and improves the proptest to cover more corner cases
=> Hotfix: RMS Norm

data/src/datum.rs, data/src/tensor.rs, linalg/src/frame/pack.rs, metal/src/memory/pool.rs
=> simplify alignment logic

.github/workflows/examples.yml, .github/workflows/full.yml, examples/pytorch-albert-v2/ci.sh
starting with transformers refactoring done between 4.50.3 to 4.51 [init_empty_weight](https://github.com/huggingface/transformers/blob/main/src/transformers/modeling_utils.py#L134) can be missing definition depending on package installed (this will likely be fixed shortly in their lib), still enabling 'accelerate' reference implem of this def solve the problem as of now.
=> fix: do not forget to accelerate

transformers/causal_llm/Cargo.toml, transformers/causal_llm/src/lib.rs
- allows to load from bytes
- allows to use wasm with this crate (tokenizers wasm features enable)
- add repeat penalty to avoid repeating in generation.
=> Feat: better wasm llm (small tweaks)
