sonos/tract

cli/src/errors.rs
core/src/errors.rs
core/src/ops/array/pad.rs
core/src/ops/nn/padding.rs
onnx/Cargo.toml
onnx/src/ops/array/mod.rs
onnx/src/ops/math.rs
onnx/src/ops/mod.rs
onnx/src/ops/nn/mod.rs
onnx/src/pb_helpers.rs
rustfmt.toml

As I've started writing pb config parser for tree-ml nodes, I figured it might be helpful to refactor protobuf getters a bit.
This brings an easier way to parse all kinds of ints, vecs/tvecs etc, with less boilerplate.
It's not just a refactor, a few functional changes as well, stricter validation:
- Trying to convert an int64 pb value into an integer type that can't contain it would now raise a descriptive error (especially with all the `usize` values); this also works with vecs/tvecs. In the current version, it would happily convert an `-1i64 as usize`; here, it would complain loudly. Ideally, all occurences of `as usize` in the codebase should also be double-checked.
- Booleans are now restricted to 0 and 1 (this was also inconsistent, in some places it was checking for 1, in some …

Refactor NodeProto ONNX pb helpers

---

harness/onnx-test-suite/build.rs

Allows you to do a plain cargo build in the base directory.

Disable onnx tests on Windows, until they can be fixed.

---

onnx/src/ops/math.rs
tensorflow/src/ops/math.rs

AddV2 is a new operator that Tensorflow 2 likes to emit. As per the documentation it is identical to Add. Compare https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/add-v2 to https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/add ...
I don't understand what the point of this op is, but this simple workaround fixes my problem :)
Could also of course duplicate the functions, but until I can find information about what makes AddV2 different, I think this is better...
Fixes #180

Initial support for AddV2

---

linalg/arm64/arm64simd/arm64simd_smmm_8x8.tmpl

Came across this bug trying to compile for iOS.
I wasn't able to link to _arm64simd_smmm_8x8 since ios is not a valid target_family. Changed to check against target_os instead. (assuming this is the intended check and not family == unix)
https://doc.rust-lang.org/reference/conditional-compilation.html#target_os

Checking os == ios instead of family == ios

---

linalg/Cargo.toml
linalg/build.rs

The old version depended on an old syn version that we don't want in our deps.
By the way, was wondering why in the world tract would use a templating engine - a macro assembler was an unexpected but clever usecase!

Upgrade liquid to 0.20

---

core/src/model/compact.rs
core/src/model/mod.rs
core/src/model/model.rs
core/src/model/patch.rs
core/src/model/translator.rs
examples/jupyter-keras-tract/src/main.rs
examples/pytorch-resnet/src/main.rs
examples/tensorflow-mobilenet-v2/README.md
examples/tensorflow-mobilenet-v2/src/main.rs
onnx/src/model.rs
tensorflow/src/model.rs

- Added `with_xxx` convenience methods to allow building models in a more fluent style.
- Added `into_runnable` model which returns a `type RunnableModel<F, O, M> = SimplePlan<F, O, M>` to more fluently create runnable models.
I noticed an inconsistency in that `set_output_label` did not return a `TractResult<()>` like other `set_xxx` methods so I went ahead and fixed that.
I also converted the examples to use the new syntax. If you don't want to do that just yet I'm fine with undoing it.

Add with_ convenience methods, add into_runnable

---

linalg/build.rs

This fixes an issue where targeting `x86_64-pc-windows-msvc` from a non-windows host would fail due to explicit usage of `lib.exe` and `ml64.exe`. The code now assumes that if that target is used from a non-windows host, the compiler is capable assembling files with the GAS syntax instead.

Fix cross compiling to Windows with clang-cl

---

onnx/src/model.rs

Add 'ai.onnx' as a valid default domain name.
I did not found any official documentation that state that it is a possiile value for the default domain but I have a model that use it and I found it mentioned here as a default domain:
https://github.com/onnx/onnx/issues/688
https://github.com/onnx/onnx/blame/master/onnx/version_converter/convert.h

Add 'ai.onnx' as default domain

---

linalg/x86_64/fma/fma_mmm_f32_16x6.tmpl
linalg/x86_64/fma/fma_mmm_i8_8x8.tmpl

We encountered an error while compiling `tract-onnx` for `--target x86_64-apple-ios` due to hard-coded os checks in some `.tmpl` files of `tract-linalg`.
```
error: linking with `cc` failed: exit code: 1
= note: Undefined symbols for architecture x86_64:
"_fma_mmm_i8_8x8", referenced from: ...
"_fma_mmm_f32_16x6", referenced from: ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
This pr fixes the issue for the given target, it might still occur for other targets.

add ios to fma matmul

---

core/src/ops/quant.rs
harness/onnx-test-suite/node-1.6.0.txt
harness/onnx-test-suite/node-1.7.0.txt
onnx/src/ops/quant.rs

This PR implement the onnx operator [DynamicQuantizeLinear](https://github.com/onnx/onnx/blob/master/docs/Operators.md#DynamicQuantizeLinear).
I could not reuse `quantize_linear_u8` because it does `x * scale.recip()` instead of `x / scale`, This change some number enough to be rounded to another integer and the onnx testsuite fails.
Is not currently possible to implement it using the operations already provided (like is done in the `dynamicquantizelinear_expanded` test) because not all needed operations are `TypedOp` and in particular `QuantizeLinear` expect the zero point and the scale to be constant tensor.
Close #380

Implement DynamicQuantizeLinear

---

core/src/ops/matmul/mir.rs
core/src/ops/quant.rs
harness/onnx-test-suite/node-1.5.0.txt
harness/onnx-test-suite/node-1.6.0.txt
harness/onnx-test-suite/node-1.7.0.txt
onnx/src/ops/math/mat_mul_integer.rs

Allow onnx operators `MatMulInteger` and `QLinearMatMul` to read `zero_point` and `scale` from the input at evaluation time when they are not constant.
Close #389

Get scale and zero_point from inputs

---

nnef/Cargo.toml
nnef/src/framework.rs

Problem: The code for reading an NNEF model file with ext `.tgz` is not taking care of the GZ decoding.
Quick Solution: Added flate2 library to decode the file before read by tar.
Ideal Solution: Detect the file extension and add GZ decoding for `.tgz` file only. But it is not in scope as the NNEF tools always generate `.tgz` file.

Fix NNEF model reader

---

hir/Cargo.toml

This is mainly because tract-pulse depends on ctor that does not work on wasm. tract-pulse is only used in tests.

Move pulse to dev deps

---

core/src/ops/matmul/mir_quant.rs
core/src/ops/mod.rs

**Problem**
during the work on #413 we encountered indexing errors in the qparams inlining during codegen under certain circumstances, depending on the relative order of the inputs compared to the order of qparams. for example at one point of the codegen we have the following node
```rust
Node {
id: 119,
name: "MatMul_101_quant",
inputs: [117/0>, 117/2>, 118/0>],
op: QMatMulUnary {
a: 1,128,512,I8 35, 39, -1, 30, -13, -25, 32, 8, -19, 6, 33, 47...,
bias: None,
a_trans: true,
b_trans: true,
c_trans: true,
output_type: I32,
params: MatMulQParams {
a0: Input(2),
a_scale: Attr(,F32 1),
b0: Input(1),
b_scale: Attr(,F32 1),
c0: Attr(,I32 0),
c_scale: Attr(,F32 1),
},
},
outputs: [1,64,512,I32 >120/0],
}
```
where the inputs are `b`, `b0` and `a0` and the inlining is going to replace the `a0`, …

fix relative indexing in qparams inline static & add tests

---

core/src/ops/element_wise.rs
core/src/ops/matmul/mir_quant.rs
core/src/ops/matmul/mir_quant_unary.rs
core/src/ops/mod.rs
core/src/ops/quant.rs
data/src/tensor.rs

**Problem**
fixes #413 
**Solution**
`tract-data`:
- add `Tensor::offset_u8_as_i8()` to apply the offsetting to a tensor elementwise
`tract-core`:
- add `ops::quant::OffsetU8asI8` operation to be wired in the quantized matmul
- conditionally wire the offsettings in `QMatMul` and `QMatMulUnary` in the evaluation and decluttering/codegen
- generalize the existing quantized matmul tests with a macro and add new test cases for the various i8-u8 combinations
**Open Questions**
- how to handle the `bias` term is a bit unclear to me. it is always of type `i32` and the way it is used in `wire_matmul_quant()` means that it is only affected by the scales but not the zero points (i would assume that the bias is expected to be given in a scaled form, but this would affect the computation of the …

qmatmul for i8xu8 and friends

---

cli/src/tensor.rs
onnx/src/ops/resize.rs

- The first commit fills in several missing arguments to `{:?}` in tract-onnx. Without this, the error message would literally be "Neither shape not scale makes sense: input_shape: {:?}, scale: {:?}, sizes: {:?}" with curly braces in it instead of the intended variables.
- The second commit is added for future compatibility with https://rust-lang.github.io/rfcs/2795-format-args-implicit-identifiers.html &mdash; if `{size}` and `{type}` in a format string without arguments were to start trying to interpolate a variable called `size` and `type`, the original code would be problematic.

Fix missing fmt argument in error message

---

hir/src/ops/array/array_feature_extractor.rs

This MR fixes an error introduced in #581 by properly checking the second input's rank.

ArrayFeatureExtractor: Fix rank check for second input

---

hir/src/ops/array/array_feature_extractor.rs

I am terribly sorry, but I seems I previously misunderstood the operators description with regards to the possible ranks and dimensions of the indices tensor.
This MR thus fixes the rank check for the output tensor, no longer assumes the indices to be of rank 1 and correctly calculates the outputs dimensions.

ArrayFeatureExtractor: Use rank check from gather, don't assume indices of rank 1

---

linalg/build.rs

std::fs::read_dir returns entries in a platform dependent order. This variability introduces inconsistent build artifacts across platforms. This is since when assembling source files, the output of the C compiler changes depending on the order in which source files are passed.
In practice this means inconsistent builds across machines, even when building from within an identical docker container.

Fix inconsistent builds by sorting dir_entries

---

linalg/Cargo.toml

Liquid 0.24 includes https://github.com/cobalt-org/liquid-rust/pull/460 which removes `chrono`, this gets rid of two CVEs
- https://rustsec.org/advisories/RUSTSEC-2020-0159.html
- https://rustsec.org/advisories/RUSTSEC-2020-0071.html
Neither of these CVEs affected tract, but this means users won't get spurious errors if they use eg [cargo-audit](https://github.com/rustsec/rustsec) or [cargo-deny](https://github.com/EmbarkStudios/cargo-deny)

Bump liquid to 0.24

---

onnx/src/ops/resize.rs

I was getting incorrect results from some MediaPipe models that use `Resize` nodes (after TFLite->ONNX conversion). This PR fixes at least one of the issues.

Fix `CoordTransformer::HalfPixel` formula

---

nnef/src/ops/core.rs
nnef/src/ops/core/range.rs
nnef/src/ser.rs

For the second issue from #718.  This is what the graph looks like:
This ends up failing with:
```
Caused by:
0: Serializing tensor "Range_1523_end.dat": ,TDim N
1: Undetermined symbol in expression: N
```
I know that the [ONNX spec for Range](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Range) says the start,end,step are scalars, so I'm wondering if rewriting Range to do the same would be prudent? It doesn't seem like I can easily convert the Tensor to another RValue for serialization.

support serialization for core::array::Range

---

harness/onnx-test-suite/node-1.6.0.txt
harness/onnx-test-suite/node-1.7.0.txt
harness/onnx-test-suite/node-1.8.1.txt
harness/onnx-test-suite/node-1.9.0.txt
onnx/src/ops/resize.rs

This PR implements the `nearest` mode for the Resize onnx op.
This is following the description in the ONNX docs (which isn't super clear but I think my implementation is right): https://github.com/onnx/onnx/blob/main/docs/Operators.md#Resize 
I have tested it by comparing the results of a [YoloV5 model](https://github.com/ultralytics/yolov5), using tract and onnxruntime. YoloV5 uses the `nearest` mode in the Resize ONNX op.
Do I have to add a unit test somewhere?

Add interpolator nearest for the Resize onnx op

---

core/src/ops/downsample/mod.rs

I add a proptest failing because of a node name duplication error when decluttering a model:
```
0 |                   -> >1/0              | Source                    a                                                  [] => [1,1,S,F32]
1 | 0/0>              -> >2/0              | Downsample                conv0.downsample                                   [1,1,S,F32] => [1,1,(S+1)/2,F32]
2 | 1/0>              -> >3/0              | Downsample                conv0.matmul-0                                     [1,1,(S+1)/2,F32] => [1,1,(S+3)/4,F32]
3 | 2/0>              -> >4/0              | Downsample                conv0.matmul-0                                     [1,1,(S+3)/4,F32] => [1,1,(S+7)/8,F32]
4 | 3/0>              -> >5/0              | MatMulUnary               conv0.matmul …
```

Fix downsample node name duplication

---

cli/src/tensor.rs
core/src/model/fact.rs
data/src/dim/tree.rs

This solves the case where you provide an `input-bundle` from CLI but have a model with arbitrary number of symbolic dimension tensors.

fix: update compatible_with to add a simple possible subtype

---

cli/src/main.rs
cli/src/run.rs

Add a tract-cli argument to dump the output tensors as an npz file.
Usage:
```
tract file.onnx --input-bundle inputs.npz -i image:3,720,1080,f32 run --save-outputs outputs.npz
```
I also added some other DatumType support for npz generation.
Removing the `unsafe` keyword for quantized tensors is intentional, it seems we don't need it.

cli: add run save-outputs argument

---

linalg/arm64/arm64fp16/arm64fp16_mmm_f16_128x1_core.tmpl
linalg/arm64/arm64fp16/arm64fp16_mmm_f16_16x8_core.tmpl
linalg/arm64/arm64fp16/arm64fp16_mmm_f16_32x4_core.tmpl
linalg/arm64/arm64fp16/arm64fp16_sigmoid_f16_8n.tmpl
linalg/arm64/arm64fp16/arm64fp16_tanh_f16_8n.tmpl
linalg/build.rs

Fixes compilation issues on the target by ensuring `-mcpu=cortex-a55` is added as a compiler flag. Before this you would end up with the error posted below. Let me know if you want a different approach (perhaps unconditionally add the flag for aarch64?)
Tested on physical Ampere Altra Arm64 machine. Issue could be seen in qemu builds as well.
```
cargo:warning=/mnt/disks/storage_disk/ark/target/debug/build/tract-linalg-de04fa2611fd2023/out/arm64fp16_sigmoid_f16_8n.S:103:5: error: instruction requires: fullfp16
cargo:warning=    fmla v28.8h, v20.8h, v0.h[2]
cargo:warning=    ^
cargo:warning=/mnt/disks/storage_disk/ark/target/debug/build/tract-linalg-de04fa2611fd2023/out/arm64fp16_sigmoid_f16_8n.S:105:5: error: instruction requires: fullfp16
cargo:warning=    fmla v24.8h, v20.8h, v28.8h …
```

Update compiler flags for aarch64-unknown-linux-gnu

---

.travis/cross.sh
cli/src/params.rs
hir/src/ops/expandable.rs
onnx-opl/Cargo.toml
onnx-opl/src/lib.rs
onnx-opl/src/multinomial.rs
onnx/Cargo.toml
onnx/src/model.rs
onnx/src/ops/mod.rs
onnx/src/ops/multinomial.rs

Add [ONNX Multinomial Operator](https://github.com/onnx/onnx/blob/main/docs/Operators.md#Multinomial).
> Generate a tensor of samples from a multinomial distribution according to the probabilities of each of the possible outcomes.
This is useful for GPT-like models, as a source of randomness for text generation.
There are no harness tests for this operator, because the outputs are random, and even though you can seed this random on the operator ; i would guess that the ONNX runtimes are not expected to output the same results.
This makes it difficult to test this operator.
What do you think? Should I add a bare minimal CI test that only checks if the eval functions doesnt crash, without checking any output?

Add ONNX Multinomial Operator

---

nnef/src/deser.rs
nnef/src/ops/core.rs
nnef/src/ops/core/shape_of.rs
nnef/src/ops/nnef/deser.rs

Allow to build NNEF models that propagate symbolic values like streaming dimension though the graph (beyond input and output current limitation).
This feature goes explicitly against NNEF spec that deprecated the practice, but is needed given the objective of `tract-nnef`.
Indeed, in our case, we want to express symbolic dimension such as streaming within the dumped graph (`graph.nnef` file).
This need arise since concretization of those symbols may be done only at inference time.
For example, in an internal case : using `tile` with a number of repeats being the number of frames in time dimension (so sample dependant).
Here are a few toy examples of working behaviours:
```
version 1.0;
extension tract_registry tract_core;
extension tract_pulse_streaming_symbol;
graph net_basic(input_0) -> …
```

Feat: tract core shape of

---

.travis/bundle-entrypoint.sh
.travis/cli-tests.sh
cli/src/bench.rs
cli/src/compare.rs
cli/src/dump.rs
cli/src/main.rs
cli/src/params.rs
cli/src/profile.rs
cli/src/run.rs
cli/src/tensor.rs
cli/src/utils.rs
doc/cli-recipe.md
harness/nnef-test-cases/conv-with-batch/runme.sh
kaldi/test_cases/run_all.sh
onnx/test_cases/run_all.sh

Motivation #797
I did not change the CI (yet?)
Not sure this is the cleanest
I only changed the `run` command for `--input-from-bundle`. You were talking about `dump` / `compare` too but i'm not sure I understand: dump does not run the model, compare only uses random input, right?

Split --input-bundle into --input-facts-from-bundle and --input-from-bundle

---

cli/src/utils.rs
hir/src/infer/fact.rs
hir/src/infer/factoid.rs
hir/src/ops/array/shape.rs
onnx/src/model.rs
onnx/src/tensor.rs
onnx/test_cases/run_all.sh
tensorflow/src/ops/array/mod.rs

Some ONNX models have symbols in their type info,
Resnet18 v2-7 example: `float32[N,3,224,224]` where N is the batch size.
Right now, we have to add the input facts ourselves in this case, otherwise it'll error. This PR fixes that :)

Translate symbols shapes in ONNX file loading

---

linalg/Cargo.toml
linalg/src/lib.rs

Hello Mathieu,
It looks like tract-core does not use the `libc` crate, yet it was part of the Cargo.toml and used with an extern crate declaration. I removed it, it still compiles and there is no regression on the test suite.

Remove the unused libc crate from tract-core dependencies

---

core/src/ops/matmul/mir_unary.rs
harness/core-proptest-pulse/Cargo.toml
harness/core-proptest-pulse/src/einsum.rs
harness/core-proptest-pulse/src/lib.rs
onnx-opl/src/einsum/expr.rs

See #792
Not sure if I implemented the test correctly. Currently, also the first test without pulse is failing:
```
---- einsum::einsum_bmm stdout ----
thread 'einsum::einsum_bmm' panicked at 'called `Result::unwrap()` on an `Err` value: running pass ChangeAxes
Caused by:
0: Making patch for AxisChange { outlet: 1/0>, op: Rm(3) } from #1 "einsum.add_m_axis" AddAxis
1: Propagating AxisChange { outlet: 1/0>, op: Rm(3) } to node #2 "einsum.mm" MatMulUnary
2: Remove a non-1 axis: axis 1 in 1,8,2,4,F32 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...', harness/core-proptest-pulse/src/einsum.rs:18:23
stack backtrace:
0: rust_begin_unwind
at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
1: core::panicking::panic_fmt
at …
```

Add test case for pulsed einsum

---

linalg/src/arm64.rs

This is just a quick fix for systems that aren't Linux (e.g. FreeBSD), falling back on /proc/cpuinfo causes trouble.
I think for special platforms, it's probably better to have some form of override available like getrandom does, because unfortunately I'm not aware of any way to pull the target_cpu if it's been specified...

Avoid trying to check /proc/cpuinfo when the system isn't Linux

---

nnef/src/tensors.rs

- add NNEF bool tensor deserialization
- add NNEF quantized "types" mapping to tract types

feat: add missing types conversion between NNEF 1.0.5 and tract 

---

examples/pytorch-albert-v2/src/main.rs

Hi there,
I found a bug while running the example `pytorch-albert-v2`. It gives the following error:
```
Error: Failed analyse for node #1470 "Add_1433" Add
Caused by:
0: Infering facts
1: Applying rule outputs[0].shape == 1,9,30000
2: Unifying shapes b,s,30000 and 1,9,30000
3: Impossible to unify Sym(Symbol('b', 0)) with Val(1).
```
After a short discussion with @cchudant, he told me calls to the function `with_input_fact` were not required anymore.
Removing them fixes the problem

Fix facts inference on example pytorch-albert-v2

---

linalg/build.rs

This fixes an issue where targeting `x86_64-apple-darwin` would unconditionally invoke `xcrun` to get `ar`, which won't work on non-macos hosts (usually). Initially I made it respect the `AR/_<cfg>` etc environment variables, but then realized the code could just, be the default, and I'm unsure why it was explicitly assembling each file and manually adding them to the archive? This method works on a linux host at least, so if CI works on a normal macos host I think it should be fine.

Fix `x86_64-apple-darwin` cross compilation

---

core/src/ops/math/mod.rs

- disable declutter in declutter_neutral if uniform type is quantized since it leads to casting error. 
Original bug: NNEF loaded QLinear without bias leads to creation of a uniform quantized tensor, that crashed at declutter due to this

fix: avoid declutter case that cast uniform quantized dtype to i64

---

core/src/model/graph.rs
core/src/model/typed.rs
core/src/optim/slice.rs
hir/src/ops/cnn/conv.rs
tensorflow/src/ops/nn/conv2d.rs

* substiture constants as soon as wire_node
* paranoid assert should not be set by default (#963)
* semi-adhox fix for slice of broadcasted dim

substiture constants as soon as wire_node (#965)

---

nnef/src/ops/nnef/ser.rs

All is in the title,
if 2 pools are used with 1 sum and another mean without this fix it create a name collision that shadow all but 1st pooling fragment at serialization.

fix: avoid name colision between different pools in nnef dumps

---

linalg/arm64/arm64simd/arm64simd_mmm_f32_12x8_core.tmpl
linalg/arm64/arm64simd/arm64simd_mmm_f32_16x4_core.tmpl
linalg/arm64/arm64simd/arm64simd_mmm_f32_24x4_core.tmpl
linalg/arm64/arm64simd/arm64simd_mmm_f32_64x1_core.tmpl
linalg/arm64/arm64simd/arm64simd_mmm_f32_8x8_core.tmpl
linalg/arm64/arm64simd/arm64simd_mmm_i32_64x1.tmpl
linalg/arm64/arm64simd/arm64simd_mmm_i32_8x8.tmpl

According to ARM documentation:
- x19-x29 needs to be callee preserved
- v8-v15 needs to be callee preserved
I might have been a bit too exhaustive (some registers might not be altered during the subroutine processing but I took the choice to persist all the resisters that needs to be persisted anyway in that first version of the PR). For sure it's a tradeoff between minimising load/stores instructions from the stack and ensuring the code is safe without having to look into the subroutine code.
Let's discuss that here

Ensure callee saved registered are properly restored

---

core/src/ops/logic.rs
core/src/ops/logic/ite.rs
hir/src/infer/model.rs
onnx/src/ops/logic.rs

ONNX If only works has a loading macro expansion: the condition must be known and fixed at loading time, the right branch is substituted in the type phase. This blocks Silero VAD v4 (see #1029).

Improve if op

---

cli/Cargo.toml
core/Cargo.toml
data/Cargo.toml
examples/jupyter-keras-tract-tf1/Cargo.toml
examples/jupyter-keras-tract-tf2/Cargo.toml
examples/nnef-dump-mobilenet-v2/Cargo.toml
examples/nnef-mobilenet-v2/Cargo.toml
examples/onnx-mobilenet-v2/Cargo.toml
examples/pytorch-resnet/Cargo.toml
examples/tensorflow-mobilenet-v2/Cargo.toml
examples/tflite-mobilenet-v3/Cargo.toml
ffi/Cargo.toml
harness/core-proptest-pulse/Cargo.toml
harness/lstm-proptest-onnx-vs-tf/Cargo.toml
harness/nnef-inceptionv3/Cargo.toml
harness/tf-inceptionv3/Cargo.toml
harness/tf-mobilenet-v2/Cargo.toml
harness/tf-moz-deepspeech/Cargo.toml
hir/Cargo.toml
libcli/Cargo.toml
linalg/Cargo.toml
nnef/Cargo.toml
nnef/nnef-resources/Cargo.toml
onnx-opl/Cargo.toml
onnx/Cargo.toml
pulse-opl/Cargo.toml
pulse/Cargo.toml
tensorflow/Cargo.toml
test-rt/test-onnx-core/Cargo.toml
tflite/Cargo.toml

The new recommendation is to follow the SPDX 2.1 standard. This allows automatic license verification software to work properly. Reference: https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields

Update license field following SPDX 2.1 license expression standard

---

core/src/ops/array/concat.rs
core/src/ops/cnn/conv/lazy_im2col.rs
core/src/ops/matmul/lir_unary.rs
core/src/optim/mod.rs
linalg/src/frame/mmm/input_store.rs
linalg/src/x86_64_fma.rs

slicing concat on another axis

---

core/src/ops/quant.rs
hir/src/ops/array/flatten.rs
hir/src/ops/nn/layer_max.rs
hir/src/ops/nn/mod.rs
hir/src/ops/nn/reduce.rs
onnx/src/ops/cumsum.rs
onnx/src/ops/mod.rs
onnx/src/ops/nn/reduce.rs

Fixes #1214 by making various modules and op attributes public.

adding public visibility

---

onnx/src/model.rs
onnx/src/tensor.rs
tensorflow/src/model.rs

Tract used to work fine with emscripten but recent changes broke that, the fix is super minor. Cheers.

Emscripten support fixes

---

examples/onnx-mobilenet-v2/README.md
examples/tensorflow-mobilenet-v2/README.md
examples/tflite-mobilenet-v3/README.md

* 'Diplay' should be 'Display'

Examples: Fix typos in example readme

---

cli/src/params.rs

Resolves #1279 on the cli by creating a routine within the --set feature of the tract cli which: 
1. Iterates over all constants in the graph 
2. If const's the inner tensor type is of type TDim then: 
a) extract that tensor
b) _evaluate_ the inner values using the symbol_values map previously established
3. _then_ concretize_dims for the entire graph 
Have confirmed that this update works on the network file provided in #1279

 fix: set constant inner tensor values upon "setting" variables 

---

Cargo.toml

Just a minor bump to reduce duplicated crates in the dependency tree of consumers.

Update `itertools` from `0.10.1` to `0.12.1`

---

core/src/ops/einsum/codegen.rs
core/src/ops/einsum/mod.rs
core/src/ops/logic.rs
data/src/dim/tree.rs
harness/nnef-test-cases/load-store/expected
harness/nnef-test-cases/tdim-cmp/graph.nnef
harness/nnef-test-cases/tdim-cmp/runme.sh
nnef/src/ops/nnef/deser.rs
nnef/src/registry.rs

- support TDim for others cmp operators

fix: tdim for other logic operators

---

core/src/ops/binary.rs
core/src/ops/element_wise.rs
core/src/ops/logic.rs
core/src/ops/nn/mod.rs
core/src/ops/quant.rs
data/src/tensor.rs
hir/src/ops/element_wise.rs
nnef/src/registry.rs
onnx-opl/src/is_inf.rs
onnx/src/ops/cast.rs
test-rt/suite-unit/src/conv_q.rs
test-rt/suite-unit/src/lib.rs
test-rt/suite-unit/src/q_binary.rs
test-rt/suite-unit/src/q_elmwise.rs
test-rt/suite-unit/src/q_flavours.rs
test-rt/suite-unit/src/q_helpers.rs
test-rt/test-tflite/suite.rs

This PR is a follow-up of binary op quantization for unary ops (like activations).
- increase precision of q for binary by removing unnecessary `scale_by`
- add output datatype for all unary operations from NNEF
- use this output datatype for the dequant->f32 op->requant default ops
- add prop-test problem for unary (refactor joint with binary)
- add sigmoid default basic q implementation

Feat: elmwise unary ops quant unaligned zp scale

---

nnef/src/deser.rs

NNEF deserialization can fail if a floating-point whole number is expressed as an integer. For example "1" instead of "1.0" results in `Can not build a f32 from Dim(Val(1))`
If `Dim.to_i64` is successful, then the result can be cast to `f32`.

Try to coerce f32 value from Dim (i64)

---

Cargo.toml
core/src/ops/array/gather_nd.rs
core/src/ops/einsum/eval.rs
data/src/tensor/litteral.rs
harness/core-proptest-pulse/src/delay_plus_downsample.rs
harness/core-proptest-pulse/src/delay_plus_pool.rs
harness/lstm-proptest-onnx-vs-tf/src/lib.rs
harness/tf-moz-deepspeech/src/lib.rs
linalg/src/frame/mmm/pack.rs
linalg/tests/virtual_im2col.rs
onnx/src/ops/nn/batch_norm.rs
tensorflow/src/conform/tf.rs
tensorflow/src/ops/nn/conv2d.rs
tensorflow/src/ops/nn/s2b/mod.rs
tensorflow/tests/ops_nn_conv2d.rs
tensorflow/tests/ops_nn_dwconv2d.rs
tensorflow/tests/ops_nn_pools.rs
test-rt/suite-unit/src/conv_f32.rs
test-rt/suite-unit/src/conv_q.rs
test-rt/suite-unit/src/deconv.rs

Blocked by https://github.com/jturner314/ndarray-npy/pull/73

Bump ndarray from 0.15.3 to 0.16

---

examples/pytorch-albert-v2/export.py

- to avoid this kind of error in the future, you may wish to freeze torch/transformers/onnx versions in pip install from `ci.sh`

fix: op_set version v14 needed at ONNX export with newer version of torch for Albert

---

metal/src/ops/sync.rs
metal/src/rewrite_rules/mod.rs
metal/src/rewrite_rules/rewire_metal_sync.rs
metal/src/transform.rs

After making MetalSyncToCpu stateful to avoid PropConst with Metal Op, some MetalSyncToCPUs were reintroduced which slow down the execution. This rewrite rule remove these ones.

[Metal] Rewrite rules: Remove MetalSyncToCPU between Const and CPU Operator

---

Cargo.toml
metal/src/memory/schema.rs

Some time is wasted in SyncToCPU ops as the inputs are in most cases ArenaView tensors we need to copy to an Owned tensor. This PR makes those outputs "Owned" so SyncToCpu only clone the reference. On OpenELM f16 the gain is of ~2%

Metal Ops Pre-SyncToCPU outputs owned tensor

---

metal/src/context.rs

Fix to resolve [Undefined behaviour on Metal empty allocation](https://github.com/sonos/tract/issues/1635)

Avoid allocating zero-sized buffer in metal-rs

---

metal/src/kernels/nn/nn_ops.metal
metal/src/kernels/nn/rms_norm.rs

Base RMSNorm Kernel was using a single SIMD Group for computing. This led to very low thread occupancy for executing the Op and hence low performance.
This PR fixes this issue by parallelizing the computation and also adds a kernel for optimizing a specific configuration (iter axis == inner axis, dim %4 == 0) present in all RMS layers of every LLM model seen
This leads to a bump of ~15 token/s on TG128 benches for most models

Metal: Improve RMS norm

---

core/src/ops/einsum/optimize.rs
test-rt/suite-unit/src/bin_einsum.rs

Einsum_as_matmul rule is adding unecessary axes to A and B when m axis is not present in the output (m dimension is necessarily 1 in those cases).
The PR makes the rule more flexible to this

Fix Einsum rule

---

core/src/ops/einsum/optimize.rs
metal/src/rewrite_rules/remove_matmul_broadcast.rs
metal/src/transform.rs

[Previous PR](https://github.com/sonos/tract/pull/1700) was missing to unwrap Symbolic dimensions to i64::Max so they were never considered. This PR fixes it
The PR also changed the rule to detect an alternative pattern to the Move(0,1) before the Matmul which can be in some models Rm(0), Add(1)

Fix symbolic dimensions considered as None in ensure_mkn

---

core/src/ops/array/gather.rs

In most cases, data is contiguous and we are copying sub-matrices along the given axis. In this case, doing block copies instead of element by element is significantly faster (for PP512 with Llama-1B-F16 on intel i9: 25ms -> 0.06ms!!).

Improve Gather: Block Copy

---

cuda/src/context.rs
cuda/src/tensor.rs
gpu/src/device.rs
gpu/src/memory/pool.rs
gpu/src/session_handler.rs
gpu/src/tensor/mod.rs
metal/src/context.rs

Directly doing an allocation on the Device side instead of creating an uninitialized Tensor on Host and copying it to Device.
This changes nothing for Metal since we are using shared memory anyway.

Fix CUDA uninitialized allocations

---

Cargo.toml

Thanks for open-sourcing and maintaining such a fast onnx model inference implementation! It's been great for my project https://github.com/jackrr/eymo! Much more performant than when I was using [ort](https://github.com/pykeio/ort) to call out to ONNX runtime.
I've recently run into this minor issue using the crate alongside [wgpu](https://github.com/gfx-rs/wgpu).
wgpu depends on half=^2.5, so is mutually incompatible with tract pinned to half=2.4.1.
I don't know the `tract` implementation details well enough to claim this is a safe change to make, nor do I believe that the integration testing with `half=2.6.0` verified by my project is sufficient enough. But I figured I'd open this up since I'd made the fork to unblock my project.

fix: loosen half crate dependency for compatibility with wgpu

---

gpu/src/memory/pool.rs
gpu/src/memory/schema.rs

Storing output offsets for node in a hashmap is slow, replace with TVec<TVec<>> for faster access

Fix Mem Pool Slowdown
